### PR TITLE
Completion image upload, fix negation of defaults, svg support, improve defaults

### LINKED ISSUE #2: Add possibility to upload icons
Especially the smiley configuration only makes sense if it is possible to upload the according icon as well. But the mime and interwiki configuration would also benefit from that.

### LINKED ISSUE #33: Support of overwritting/negation of default values
Dokuwiki allows negation in local config of default config values.
See also https://github.com/splitbrain/dokuwiki/pull/1158

### LINKED ISSUE #55: SVG smileys with the coming DokuWiki release
The new smileys are svg instead of gif.
The confmanager only supports gif, jpg and png at the moment.

https://github.com/cosmocode/confmanager/blob/9a7e0435ea1b5b2f6c6a8c2ee1cd26d542c0e9a8/action/registerconfig.php#L69-L72

### PR DESCRIPTION
**Pull request by Klap-in**
In addition to #31 
- Updates config value after image upload as well

Closes #2 - this PR finalize the smiley upload by using the upload stuff added earlier to this plugin.

- Fixes #33 
- Fixes #55 (breaks backward compatibility for file icons)
- show error messages if error occurs
- show in interface if a value overrides/is overridden visually and with a note

See further the commit messages.

Some extra testing is welcome, as this affects configuration files.

### CODE REVIEW

**Comment by Klap-in** [comment]
**Question:**
Are there characters not allowed as filename for smileys? So far I don't check/clean this path/filename.

**Comment by splitbrain** [comment]
There are no real limits, but it might be a good idea to simply limit them to valid pagenames?

**Comment by Klap-in** [comment]
Is that not too strict?

**Comment by Klap-in** [comment]
I think this is now ready for merging.

**Comment by splitbrain** [comment]
thank you :pray:

**Pull request merged**
